- cover: "/images/books/1.png"   # 书籍封面图片，以public为根目录的绝对路径
  title: "大数据十讲"             # 书名
  authors: "周烜 陈志广"          # 作者
  description: >                 # 简介（可换行，实际显示时会忽略换行符）
    当下，大数据已成为互联网、人工智能和数字化转型等的基础理论，
    宏观了解大数据前沿理论与技术，
    对于大数据方向的研究人员以及从事大数据开发的工程师来讲至关重要。
    本书由多位大数据领域专家学者合作完成，通过10章内容，
    深入浅出地阐述大数据的完整前沿知识体系，帮助读者以宏观视角把握大数据的发展方向和突破口，
    真正从普通开发者晋升为拥有大数据思维并能解决复杂问题的技术专家。 
    本书既可作为大数据方向低年级研究生研究大数据技术的入门指南，
    也可作为从事大数据研究的科研人员的参考书。
- cover: "/images/books/2.png"
  title: "云原生数据库：原理与实践"
  authors: "李飞飞 周烜 蔡鹏等"
  description: >
    本书深入剖析了云计算时代数据库技术的演进历程，从架构设计、实现机制与系统优化等多维视角，
    阐释了传统数据库技术如何逐步发展到云原生形态。
    书中强调理论与实践结合，解析MySQL、PostgreSQL等工业界系统实现数据库的SQL优化与执行、
    事务处理、缓存与索引等原理，揭示了数据库在面对实际应用需求时所做的权衡，
    以及在复杂场景下的优化策略背后的逻辑。
    本书可作为高等院校信息类专业的本科生和硕士研究生教材，
    也可作为数据库行业的内核研发和系统运维等从业人员的参考书。
- cover: "/images/books/3.png"
  title: "云原生数据仓库：原理与实践"
  authors: "李飞飞 周烜 胡卉芪等"
  description: >
    本书深入地探讨云原生数据仓库的理论知识与技术实践，
    主要内容涵盖数据仓库的发展历程、大数据处理技术、云原生数据仓库的概念与特点，
    以及云计算时代的数据仓库技术。书中详细介绍云原生数据仓库的架构设计，
    计算引擎、优化器、存储的关键技术，以及资源管理与调度等知识。
    同时，本书结合Redshift、Snowflake、BigQuery等典型的云原生数据仓库，
    以及 AnalyticDB等代表性的国产数据仓库介绍大量的实践案例。
    此外，书中针对云原生数据仓库的资源调度、查询优化、运维管理等方面进行深入的剖析，
    提供大量的最佳实践和应用场景。
- cover: "/images/books/4.png"
  title: "分布式计算系统"
  authors: "徐辰"
  description: >
    本书聚焦于 Hadoop、Spark、Flink 等面向数据密集型应用的分布式计算系统，
    将原理、架构、编程的知识进行有机结合，
    统一从设计思想、体系架构、工作原理、容错机制和编程示例5个维度进行剖析。
    本书注重通过横向比较阐释该类系统设计的共性原理，
    帮助读者形成完整、统一的知识体系。
- cover: "/images/books/5.png"
  title: "当代数据管理系统"
  authors: "周烜 周欢 赵明昊"
  description: >
    本书的内容的主线是一系列数据管理系统的通用知识，包括数据系统的概念、
    数据模型和查询语言的概念、数据存储技术、事务处理技术、查询处理技术、
    数据库设计的基本方法等。将这些通用知识在特定的数据管理系统上进行展开，
    就得到具体系统的使用方法和实现原理。
    通过这种方式，本书将传统SQL数据库、文档数据库、图数据库等数据管理系统的知识都囊括了进来。
- cover: "/images/books/6.png"
  title: "Cloud Native Database Principle and Practice"
  authors: "Feifei Li, Xuan Zhou, Peng Cai, et al."
  description: >
    This book analyzes in detail the technological evolution process of databases 
    in the era of cloud computing and explains how traditional database technology 
    has gradually developed to cloud-native form 
    from multiple perspectives such as architecture design, 
    implementation mechanism, and system optimization. 
    This book emphasizes the full combination of theory and practice 
    and also analyzes the SQL optimization and execution, 
    transaction processing, caching and indexing principles of databases 
    implemented by MySQL, PostgreSQL and other systems, 
    what trade-offs and compromises are made in the face of actual application requirements, 
    how to optimize in the face of complex application scenarios, 
    and the reasons behind making various choices. 



