- cover: "/images/books/1.png"
  title: "大数据十讲"
  authors: "周烜 陈志广"
  description: "当下，大数据已成为互联网、人工智能和数字化转型等的基础理论，宏观了解大数据前沿理论与技术，对于大数据方向的研究人员以及从事大数据开发的工程师来讲至关重要。本书由多位大数据领域专家学者合作完成，通过10章内容，深入浅出地阐述大数据的完整前沿知识体系，帮助读者以宏观视角把握大数据的发展方向和突破口，真正从普通开发者晋升为拥有大数据思维并能解决复杂问题的技术专家。 本书既可作为大数据方向低年级研究生研究大数据技术的入门指南，也可作为从事大数据研究的科研人员的参考书。"
- cover: "/images/books/2.png"
  title: "云原生数据库：原理与实践"
  authors: "李飞飞 周烜 蔡鹏 张蓉 黄贵 刘湘雯"
  description: "阿里云智能数据库事业部总负责人李飞飞博士，华东师范大学数据科学与工程学院副院长周烜教授，领衔撰写！\n\n阿里云数据库领域数十年的研发实践经验结晶\n\n兼具理论深度和实践细节，启发深入思考\n\n开放性地探索数据库前沿发展方向\n\n诠释云原生分布式数据库4大核心技术：资源池化、弹性扩展、智能运维和离在线一体化\n\n详解未来数据库发展6大趋势：云原生与分布式、大数据与数据库一体化、软硬件一体化、多模数据、智能化运维、安全可信"
- cover: "/images/books/3.png"
  title: "云原生数据仓库：原理与实践"
  authors: "李飞飞 周烜 胡卉芪 杨程程 林亮 王远"
  description: "本书深入地探讨云原生数据仓库的理论知识与技术实践，主要内容涵盖数据仓库的发展历程、大数据处理技术、云原生数据仓库的概念与特点，以及云计算时代的数据仓库技术。书中 详细介绍云原生数据仓库的架构设计，计算引擎、优化器、存储的关键技术，以及资源管理与调度等知识。同时，本书结合Redshift、Snowflake、BigQuery等典型的云原生数据仓库，以及 AnalyticDB等代表性的国产数据仓库介绍大量的实践案例。此外，书中针对云原生数据仓库的资源调度、查询优化、运维管理等方面进行深入的剖析，提供大量的最佳实践和应用场景。"
- cover: "/images/books/4.png"
  title: "Cloud Native Database"
  authors: "李飞飞 周烜 蔡鹏 张蓉 黄贵 刘湘雯"
  description: "本书深入剖析了云计算时代数据库技术的演进历程，从架构设计、实现机制与系统优化等多维视角，阐释了传统数据库技术如何逐步发展为云原生形态。书中强调理论与实践紧密结合，通过解析MySQL、PostgreSQL等系统的SQL优化与执行、事务处理、缓存与索引原理，揭示数据库在面对实际应用需求时所做的权衡，以及在复杂场景下的优化策略背后的逻辑。同时，本书结合阿里巴巴集团在数据库领域的研发实践，重点探讨了现代数据库从系统到服务演进的核心技术原理——如何运用云计算资源池化技术与分布式技术，实现数据库的高可用性、弹性扩缩容与按需使用能力。"
- cover: "/images/books/5.png"
  title: "分布式计算系统"
  authors: "徐辰"
  description: "本书聚焦于 Hadoop、Spark、Flink 等面向数据密集型应用的分布式计算系统，将原理、架构、编程的知识进行有机结合，统一从设计思想、体系架构、工作原理、容错机制和编程示例 5 个维度进行剖析。本书注重通过横向比较阐释该类系统设计的共性原理，帮助读者形成完整、统一的知识体系。\n\n本书概述了分布式计算系统（第 1 章），根据应用场景的差异将分布式计算系统划分为批处理系统（第 3、4 章）、流计算系统（第 7、8 章）、批流融合系统（第 9、10 章）、图处理系统（第 11 章），并选取了各个类别中的典型代表。由于这些分布式计算系统不可能孤立地存在，因此本书也介绍了面向文件存储（第 2 章）、资源管理（第 5 章）以及协调服务（第 6 章）的系统。\n\n本书可作为高等院校数据科学与大数据技术专业高年级本科生的教学用书，以及计算机科学与技术、软件工程、数据科学与工程等专业研究生的教学用书，也可作为部分业界研发人员的参考用书。"

