label: "课程与教材建设" # 中文标题
label_en: "COURSES & TEXTBOOKS" # 英文标题
content: > # 简介（可换行，实际显示时会忽略换行符）
  团队聚焦数据库与计算机系统等基础软件相关的课程建设，
  承担当代数据管理系统，数据管理系统（拔尖基地），高级数据管理系统（数据库系统实现），
  数据库系统构建（拔尖基地荣誉课程），计算机系统（数据学院&拔尖基地荣誉课程）、
  计算机网络、分布式系统等课程的教学，与蚂蚁OceanBase、TuGraph、
  平凯星辰（PingCap）等多家知名企业合作开展协同育人项目或开展合作实践教学，
  参与“101计划”数据库系统课程虚拟教研室建设，曾多次获得省部级教学教改方面贡献奖，
  出版过多部教材与专著，在人才培养与教学探索方面取得了一定的成就。
        