label: "学院概况"
label_en: "Overview"
content: "数字经济的飞速发展为数据基础设施带来了巨大挑战。如何让数据系统充分利用云计算平台上的各类存储与计算资源，实现高效的数据管理、数据分析和建模,以应对数字化、智能化应用对数据服务的多样化需求，是近年来学界和工业界关注的核心问题，也是数据学院长期从事的科研方向。数据学院与众多企业展开合作,研制新一代数据库、数据仓库和 Al 数据管理系统，取得了丰富的科研成果，获得多项省部级和国家级科技进步奖。"