- id: "Cedar"
  title: "分布式与云原生数据库"
  description: >
    分布式与云原生数据库面向高并发和大规模数据处理需求，采用分布式一致性协议、分片副本机制和资源调度策略，以保障数据一致性与系统可用性，支持弹性扩展与自动化运维，在多租户和高动态负载等复杂云环境中展现出优越的可扩展性与稳定性。
    主要成果包括：设计了面向分布式数据库系统的工作负载驱动分层死锁检测方法（HAWK），有效应对大规模环境下的死锁检测挑战；参与研发了可扩展的元数据管理协调服务（FDBKeeper）及支持万亿级边的高吞吐图存储系统（RedTAO）；提出了面向更新密集型工作负载的自适应 LSM 引擎（SylphDB），以及适用于实时 HTAP 场景的高效日志重放框架；在并发控制方面，构建了针对异构工作负载的自适应乐观并发控制机制。
  image: "/images/projects/4.png"
  papers:
    - venue: "VLDB 2025"
      title: "HAWK: A Workload-driven Hierarchical Deadlock Detection Approach in Distributed Database System"
    - venue: "VLDB 2025"
      title: "FDBKeeper: Enabling Scalable Coordination Services for Metadata Management using Distributed Key-Value Databases"
    - venue: "SIGMOD 2025"
      title: "RedTAO: A Trillion-edge High-throughput Graph Store"
    - venue: "PVLDB 2024"
      title: "Fast Commitment for Geo-Distributed Transactions via Decentralized Co-coordinators"
    - venue: "ICDE 2024"
      title: "Log Replaying for Real-Time HTAP: An Adaptive Epoch-based Two-Stage Framework"      
    - venue: "PVLDB 2022"
      title: "Starry: Multi-master Transaction Processing on Semi-leader Architecture"
    - venue: "ICDE 2021"
      title: "SLIMSTORE: A Cloud-based Deduplication System for Multi-version Backups"
    - venue: "DASFAA 2020"
      title: "Dependency Preserved Raft for Transactions"
    - venue: "DASFAA 2020"
      title: "Migratable Paxos - Low Latency and High Throughput Consensus Under Geographically Shifting Workloads"
    - venue: "VLDB 2019"
      title: "Adaptive Optimistic Concurrency Control for Heterogeneous Workloads"
    - venue: "DASFAA 2019"
      title: "Fast Quorum-based Log Replication and Replay for Fast Databases"
    - venue: "USENIX ATC 18"
      title: "Solar: Towards a Shared-Everything Database on Distributed Log-Structured Storage"
    - venue: "DASFAA 2018"
      title: "Efficient Snapshot Isolation in Paxos-Replicated Database Systems"

- id: "PG-RAC"
  title: "高性能数据处理技术"
  description: >
    传统数据库在高并发写入和大规模分析场景下常面临性能瓶颈，难以同时满足响应速度、吞吐量和一致性要求。高性能数据处理技术通过引入持久内存、SSD 等新型硬件，提升存储与访问效率，并结合内存计算与 in-memory OLAP 架构，进一步优化事务处理与分析查询性能。  
    主要成果包括：开发了支持多写事务的共享缓存数据库 PG-RAC，优化缓存协议与路由机制，降低跨节点访问开销和事务延迟，提升高并发场景下的系统吞吐能力；提出了面向分析型数据库的高效列式引擎 Hockey，针对 PMem 与 SSD 组成的异构存储环境，设计了数据与元数据在持久内存中的组织与访问机制，并提出分层数据放置策略，以实现混合存储架构下的性能与资源利用平衡。
  image: "/images/projects/5.jpg"
  papers:
    - venue: "ICDE 2025"
      title: "Columnar Formatted Inverted Index for Highly-paralleled, Vectorized Query Processin, International Conference on Data Engineering"
    - venue: "TACO 2024"
      title: "SuccinctKV: a CPU-efficient LSM-tree Based KV Store with Scan-based Compaction"
    - venue: "PVLDB 2023"
      title: "MagicScaler: uncertainty-aware, predictive autoscaling"
    - venue: "ICDE 2023"
      title: "PM-Blade: A Persistent Memory Augmented LSM-tree Storage for Database"
    - venue: "ICDE 2023"
      title: "Workload-Aware Log-Structured Merge Key-Value Store for NVM-SSD Hybrid Storage"
    - venue: "CIKM 2022"
      title: "Hockey: A Hybrid PMem-SSD Storage Engine for Analytical Database"
    - venue: "CIKM 2021"
      title: "Jasmine: Exploring the Dependency-Aware Execution on Distributed Shared Memory"
    - venue: "TKDE 2020"
      title: "Scheduling Resources to Multiple Pipelines of One Query in a Main Memory Database Cluster"
    - venue: "DASFAA 2020"
      title: "High Performance Design for Redis with Fast Event-Driven RDMA RPCs"
    - venue: "PVLDB 2019"
      title: "Adaptive Optimistic Concurrency Control for Heterogeneous Workloads"
    - venue: "ICDE 2018"
      title: "Range Optimistic Concurrency Control for a Composite OLTP and Bulk Processing Workload"

- id: "DBHammer"
  title: "数据库测试与评测"
  description: >
    数据库系统的性能优化与评测一直是数据库领域的核心研究课题之一。我们针对事务处理、分析型查询与多模数据管理等典型场景，构建了涵盖负载生成、查询优化评估、系统行为分析与事务一致性验证的评测机制，逐步形成面向关系型与多模数据库系统的统一优化与评测体系，为系统性能调优、架构演进与稳定性保障提供了坚实支撑。
    主要成果包括：提出查询感知型数据生成方法 Touchstone 系列，显著提升复杂查询场景下的负载构造效率与数据生成性能，为分析型优化器评估提供高效支持；开发事务负载生成工具 Lauca，实现高并发事务场景的行为仿真与评估复现；设计面向分布式事务系统的性能评测基准 Dike 和适用于 OLAP 场景的自动化测试工具 Artemis，并覆盖高冲突事务与复杂连接操作等典型负载；构建通用隔离级别验证框架 Leopard 及高效测试用例生成工具 DBStorm，以增强事务语义验证的规模化与自动化能力。
  image: "/images/projects/2.png"
  papers:
    - venue: "SIGMOD 2025"
      title: "A Query-Aware Enormous Database Generator For System Performance Evaluation"
    - venue: "ICDE 2025"
      title: "Artemis: A Customizable Workload Generation Toolkit for Benchmarking Cardinality Estimation"
    - venue: "ICDE 2024"
      title: "Mirage: Generating Enormous Databases for Complex Workloads"
    - venue: "TKDE 2024"
      title: "Lauca: A Workload Duplicator for Benchmarking Transactional Database Performance"
    - venue: "ISSTA 2024"
      title: "DBStorm: Generating Various Effective Workloads for Testing Isolation Levels"
    - venue: "DASFAA 2024"
      title: "Touchstone+ : Query Aware Database Generation for Match Operators"
    - venue: "SIGMOD 2023"
      title: "Dike: A Benchmark Suite for Distributed Transactional Databases"
    - venue: "ICDE 2023"
      title: "Leopard: A Black-Box Approach for Efficiently Verifying Various Isolation Levels"
    - venue: "ICDE 2022"
      title: "Application-Oriented Workload Generation for Transactional Database Performance Evaluation"
    - venue: "TKDE 2022"
      title: "A Scalable Query-Aware Enormous Database Generator for Database Evaluation"
    - venue: "Frontiers of Computer Science 2020"
      title: "Benchmarking on intensive transaction processing"
    - venue: "USENIX ATC 2018"
      title: "Touchstone: Generating Enormous Query-Aware Test Databases"


- id: "DMIC"
  title: "面向AI的数据基架"
  description: >
    聚焦数据库系统、深度学习系统、大数据处理系统等基础软件系统的性能瓶颈，
    研发支持智能时代数据管理的基础软件系统。主要成果包括：
    设计高性能的支持AI预测查询的数据管理系统，如IMBridge；
    在算法特性、硬件架构等方面优化深度学习系统，如HyInJ、RECS；
    通过优化迭代式矩阵运算来优化基于大数据平台的机器学习系统，如ReMac、HyMAC。
    这些工作从上层应用、底层硬件等多角度出发，着力提升软件系统的执行效率。
    研究工作得到国家和上海市科技计划，以及蚂蚁、腾讯、PingCAP等合作企业的支持。
  image: "/images/projects/3.png"
  papers:
    - venue: "SIGMOD 2025"
      title: "Mitigating the Impedance Mismatch between Prediction Query Execution and Database Engine"
    - venue: "SIGMOD 2025"
      title: "Scheduling Data Processing Pipelinesfor Incremental Training on MLP-based Recommendation Models"
    - venue: "ICDE 2025"
      title: "Machine Learning Inference Pipeline Execution Using Pure SQL Based on Operator Fusion"
    - venue: "SIGMOD 2024"
      title: "Impedance Mismatch Mitigation between Database Engine and Prediction Query Execution"
    - venue: "ICDE 2024"
      title: "Hybrid Evaluation for Occlusion-based Explanations on CNN Inference Queries"
    - venue: "PPoPP 2023"
      title: "Elastic Averaging for Efficient Pipelined DNN Training"
    - venue: "SIGMOD 2022"
      title: "Redundancy Elimination in Distributed Matrix Computation"
    - venue: "VLDB 2022"
      title: "ReMac: A Matrix Computation System with Redundancy Elimination"
    - venue: "SIGMOD 2021"
      title: "Hybrid Evaluation for Distributed Iterative Matrix Computation"
    - venue: "VLDB 2021"
      title: "HyMAC: A Hybrid Matrix Computation System"

- id: "AI4DB" # 内部ID
  title: "智能自治化数据库系统" # 项目名
  description: > # 项目简介（可换行，实际显示时会忽略换行符）
    将人工智能技术应用于数据库系统的自动化优化和管理。
    主要成果包括：开发了面向分布域外工作负载的风险感知索引收益估算方法(Rainbow)，
    提高了索引推荐的准确性；
    通过多任务学习实现了功能感知的数据库调优，
    并为慢查询提供了在线索引推荐服务；
    构建了面向事务数据库的多异常数据生成系统(DB-MAGS)；
    开发了基于大语言模型的自动化跨域探索性数据分析系统 TiInsight，
    实现了数据分析流程的端到端自动化；
    构建了统一的多智能体大语言模型表格问答系统(UNITQA)和自主表格问答系统(AutoTQA)，
    大幅提升了结构化数据的问答能力；
    设计了零样本自动探索性数据分析系统(Chat2Query)，让用户能够通过自然语言交互进行数据分析。
    这些研究将机器学习、多任务学习等AI技术与数据库优化深度融合，
    实现了数据库系统的智能化管理，显著提升了系统的自动化运维能力和性能优化效果。
  image: "/images/projects/1.png" # 项目图片
  papers: # Publication List
    - venue: "VLDB 2025"
      title: "Towards Automated Cross-domain Exploratory Data Analysis through Large Language Models"
    - venue: "PVLDB 2025"
      title: "AQETuner: Reliable Query-level Configuration Tuning for Analytical Query Engines"
    - venue: "SIGMOD 2025"
      title: "UNITQA: A Unified Automated Tabular Question Answering System with Multi-Agent Large Language Models"
    - venue: "ICDE 2025" # 期刊
      title: "Learning from the Past: Adaptive Parallelism Tuning for Stream Processing Systems" # 标题
    - venue: "ICDE 2025"
      title: "Hyper: hybrid physical design advisor with multi-agent reinforcement learning. "
    - venue: "ICDE 2025"
      title: "Rabbit: retrieval-augmented generation enables better automatic database knob tuning"
    - venue: "VLDB 2024"
      title: "AutoTQA: Towards Autonomous Tabular Question Answering through Multi-agent Large Language Models"
    - venue: "SIGMOD 2024"
      title: "ByteCard: Enhancing ByteDance’s Data Warehouse with Learned Cardinality Estimation"
    - venue: "ICDE 2024"
      title: "Chat2Query: A Zero-Shot Automatic Exploratory Data Analysis System with Large Language Models"
    - venue: "ECML PKDD 2024"
      title: "LATuner: An LLM Enhanced Database Tuning System Based on Adaptive Surrogate Model"
    - venue: "ICDE 2023"
      title: "Workload-Aware Log-Structured Merge Key-Value Store for NVM-SSD Hybrid Storage"


