- name: "周傲英"
  title: "创院院长 教授 博士生导师"
  avatar: "https://dase.ecnu.edu.cn/_upload/article/images/ab/e3/5a2a35264030b424728d53c71e60/b93e7a49-2c23-4bf6-958a-c3ca1f183f2b.png"
  website: "https://dase.ecnu.edu.cn/37/5c/c41774a538460/page.htm"
- name: "钱卫宁"
  title: "教授 博士生导师"
  avatar: "https://faculty.ecnu.edu.cn/_upload/article/images/26/e1/2d311e2d42cb84a53b9d36d09849/c1b9a6f3-d5c1-40ed-9140-f4e1d8f93d84_s.jpg"
  website: "https://faculty.ecnu.edu.cn/_s37/qwn/main.psp"
- name: "周烜"
  title: "教授 博士生导师"
  avatar: "https://faculty.ecnu.edu.cn/_upload/article/images/e4/ee/a615604d4104a58036e62f7f4073/77f44ed4-c27b-40b2-b05d-c63bfbec945c_s.jpg"
  website: "https://faculty.ecnu.edu.cn/_s37/zx2/main.psp"
- name: "张蓉"
  title: "教授 博士生导师"
  avatar: "https://faculty.ecnu.edu.cn/_upload/article/images/8e/1f/cacb0d37499bbcd76e4ccf0c57fa/a052fcd2-730a-4c86-9087-74f79f29bcb7_s.png"
  website: "https://faculty.ecnu.edu.cn/_s37/zr2/main.psp"
- name: "胡卉芪"
  title: "教授 博士生导师"
  avatar: "https://faculty.ecnu.edu.cn/_upload/article/images/f9/4a/aafc8c2d403aa737a986b027885c/1788b4ef-475a-4c72-96f0-c778c8f9db28_s.png"
  website: "https://faculty.ecnu.edu.cn/_s37/hhq2/main.psp"
- name: "蔡鹏"
  title: "教授 博士生导师"
  avatar: "https://faculty.ecnu.edu.cn/_upload/article/images/fb/a1/e260487247a1864958a01cf94760/4fb029c6-4e2a-419a-a714-bd7e8ea178b0_s.png"
  website: "https://faculty.ecnu.edu.cn/_s37/cp2/main.psp"
- name: "徐辰"
  title: "教授 博士生导师"
  avatar: "https://faculty.ecnu.edu.cn/_upload/article/images/d6/6a/9911988444b096240fbf5cff6339/75d26297-652e-4a8d-86ae-4c3fe93338c5_s.jpg"
  website: "https://faculty.ecnu.edu.cn/_s37/xc/main.psp"
- name: "杨程程"
  title: "青年研究员"
  avatar: "https://dase.ecnu.edu.cn/_upload/article/images/3f/a9/348527fb4f629cea80e052706871/e101e250-82a0-427c-8ffe-b3fe41b621e7.jpg"
  website: "https://faculty.ecnu.edu.cn/_s37/ycc/main.psp"
- name: "张缴怡"
  title: "讲师"
  avatar: "/images/avatar/zjy.jpg"
  website: "https://jiaoyizhang.github.io"
- name: "赵明昊"
  title: "助理教授"
  avatar: "https://faculty.ecnu.edu.cn/_upload/article/images/02/6b/b75c1cce483c85cbcd960bfcd7b7/7b67a3e9-da84-4062-8050-2eaf38a9c885_s.jpg"
  website: "https://faculty.ecnu.edu.cn/_s37/zmh2/main.psp"
